Add Free GAEN alternative project
c4dt/showcase pull request #104
Opened 2020-10-05 15:06 UTC by cgrigis

2020-10-05 15:07 UTC, cgrigis commented
Closes c4dt/TODO#187

2020-10-05 16:45 UTC, ineiti requested changes

2020-10-05 16:45 UTC, ineiti commented on data/HexHive/projects.yaml
> +            - name:   Mathias Payer
Add yourself to the contacts

2020-10-05 16:45 UTC, ineiti commented on data/HexHive/projects.yaml
> +            - Protocol
GAEN, CoVid

2020-10-06 06:15 UTC, ineiti approved these changes

2020-10-06 06:15 UTC, merged