Add dark mode and minor adjustments to the color theme to match C4DT's logo
c4dt/showcase pull request #162
Opened 2021-03-29 09:57 UTC by LucasTrg

![photo_2021-03-29_10-11-38](https://user-images.githubusercontent.com/47852577/112820488-ef9c9a80-9085-11eb-84c3-f10a55de5441.jpg)

2021-03-29 09:59 UTC, LucasTrg commented
In order to see the dark mode, you need to set your browser preferences to dark, I believe it's supported on most modern browsers (tested on IEE, Firefox and Chrome). We could perhaps add a radio button to toggle back and forth

2021-03-30 06:53 UTC, ineiti commented
Great work. Can you please adjust the following:
- make the breadcrumb bar lighter, so it is more visible
- make the tags darker, so they stand less out

2021-03-30 12:10 UTC, cgrigis requested changes

2021-03-30 12:10 UTC, cgrigis commented on resources/styles.css
> -table.dataTable.display tbody tr.active.odd {
If I understand correctly, this removes the special `active` class.
Granted, it's not very clear :-) , but this class is actually [used](https://github.com/c4dt/showcase/blob/main/views/projects.tpl#L190) to mark the "active" projects in green (i.e. the ones whose last commit is within the last 9 months). On https://showcase.c4dt.org/, you can see that the projects towards the bottom should be mostly grey. That is unfortunately what makes the table CSS classes a bit cumbersome, as there are the alternate greys (even/odd) and the alternate greens (even/odd), in addition to the sorting versions...

2021-04-12 15:26 UTC, ineiti commented
I like the basic colors, however:
- the colors for the light mode should stay like in `main`
- when hovering over an active project, the color should stay something in the blue tone
- the tags background is still too strong - it should be darker, eventually even so dark that you need a white font
- @cgrigis changed a lot how things are done in the showcase in `main` - so you need to rebase it on that, sorry...

2021-04-23 06:01 UTC, LucasTrg commented
Thanks to @tharvik, the branch is now rebased on main properly. I decided to discard the orange for the labels as I did not find any good way to make an orange rectangle on a dark background not eye-catching. Let me know what you think. Hopefully, this commit is the last one!

2021-04-23 14:27 UTC, cgrigis requested changes
I like the non-orange tags color in dark-mode!

Two remarks:
- The "active" projects in normal-mode are still not showing for me (tested on Firefox & Chromium)
- [Minor] The legend for the "active" projects is maybe a bit too close to the C4DT logo.

2021-04-25 20:34 UTC, LucasTrg commented
Indeed, I may have messed up a commit while rebasing, I believe it's fixed now. I'm not 100% happy with how the legend looks in light mode, I might need to exaggerate the colors of the square because I can barely distinguish them (although that might be me)

2021-04-26 07:03 UTC, ineiti commented
Very nice, thank you. As a last step, I would increase a little bit the intensity of the `hover` part, it's barely visible.

2021-04-26 07:26 UTC, LucasTrg commented
Agreed ! The highlight is a bit bolder and more contrasting now

2021-04-26 08:03 UTC, ineiti commented
For dark mode I think it makes more sense to lighten the hover: #177

2021-04-26 11:28 UTC, cgrigis commented
> I believe it's fixed now.

Yes, thank you! :)

> I'm not 100% happy with how the legend looks in light mode, I might need to exaggerate the colors of the square because I can barely distinguish them (although that might be me)

Agreed. Perhaps a think black border around the colors?

2021-04-28 06:00 UTC, ineiti requested changes
need to solve conflict first

2021-05-04 14:31 UTC, cgrigis approved these changes

2021-05-04 15:03 UTC, ineiti approved these changes

2021-05-04 15:30 UTC, merged