Updates to DEDIS
c4dt/showcase pull request #168
Opened 2021-04-13 05:01 UTC by ineiti

By request of Pierluca, updates to the DEDIS repo.

2021-04-14 14:05 UTC, cgrigis requested changes
Minor points, otherwise LGTM

2021-04-14 14:05 UTC, cgrigis commented on data/DEDIS/projects.yaml
> +      The e-voting used in the EPFL voting in summer 2018 and 2020. It allows users
since 2018?

2021-04-19 08:08 UTC, cgrigis approved these changes

2021-04-19 08:10 UTC, merged

2021-04-19 08:43 UTC, ineiti commented
should've put this in Draft mode, sorry, and not asked for your review. Was not ready for merge...

2021-04-19 08:50 UTC, cgrigis commented
Oops, sorry. Want me to revert?

2021-04-19 09:57 UTC, ineiti commented
No revert necessary, I hope DEDIS will not complain ;)

Just refining the workflow a bit 
- @ineiti needs to actually mark PRs as drafts (started with #172)
- generally: only merge PRs that are in the `Ready4Merge` pipeline - not sure if we can enforce that with github