Updated LDS projects
c4dt/showcase pull request #171
Opened 2021-04-19 07:25 UTC by ineiti

2021-04-19 08:21 UTC, cgrigis requested changes
A few minor points

2021-04-19 08:21 UTC, cgrigis commented on data/LDS/projects.yaml
> +            text: "Ieee Transactions On Information Forensics And Security"
```suggestion
            text: "IEEE Transactions On Information Forensics And Security"
```

2021-04-19 08:21 UTC, cgrigis commented on data/LDS/projects.yaml
> +            url: http://www.cs.yale.edu/homes/jf/PriFi-WPES2016.pdf
If I am not mistaken, this is on the homepage of one of the paper contributors.
The conference URL seems to be:
    http://wpes2016.di.unimi.it/program

2021-04-19 08:21 UTC, cgrigis commented on data/LDS/projects.yaml
> +            url: https://www.degruyter.com/downloadpdf/j/popets.2017.2017.issue-4/popets-2017-0047/popets-2017-0047.pdf
The conference site is at: https://petsymposium.org/2017/program.php

2021-04-19 08:41 UTC, tharvik commented on data/LDS/projects.yaml
> +          - label: Published at
```suggestion
          - label: Published in
```

2021-04-19 08:41 UTC, tharvik commented on data/LDS/projects.yaml
> +        url: https://infoscience.epfl.ch/record/223389?ln=en
no need to force language of the page.

```suggestion
        url: https://infoscience.epfl.ch/record/223389
```

2021-04-19 08:41 UTC, tharvik commented on data/LDS/projects.yaml
> +        url: https://infoscience.epfl.ch/record/229308?ln=en
```suggestion
        url: https://infoscience.epfl.ch/record/229308
```

2021-04-19 08:41 UTC, tharvik commented on data/LDS/projects.yaml
> +        url: https://infoscience.epfl.ch/record/277406?ln=en
```suggestion
        url: https://infoscience.epfl.ch/record/277406
```

2021-04-26 15:48 UTC, cgrigis approved these changes

2021-04-27 06:50 UTC, merged