Updated MLO
c4dt/showcase pull request #191
Opened 2021-05-25 13:23 UTC by ineiti

2021-05-26 14:01 UTC, cgrigis requested changes

2021-05-27 11:36 UTC, ineiti commented on data/MLO/projects.yaml
> +        url: https://infoscience.epfl.ch/record/266638
Oups - no. Then let's keep the arxiv one...

2021-05-27 11:47 UTC, ineiti commented on data/MLO/projects.yaml
> +        url: https://infoscience.epfl.ch/record/278542
It is available here: `Additional link: fulltext` -> `Paper` - but it's cumbersome and not the `Download` on top that the other papers have.

I wrote to Martin to ask whether this is on purpose, or if he wants to add the PDF there.

2021-05-27 12:22 UTC, ineiti commented on data/MLO/projects.yaml
> +        url: https://infoscience.epfl.ch/record/266638
Went back to infoscience, now that martin added the pdf there.

2021-05-27 12:22 UTC, ineiti commented on data/MLO/projects.yaml
> +        url: https://infoscience.epfl.ch/record/278542
OK, PDF is added to infoscience.

2021-05-27 12:25 UTC, cgrigis approved these changes

2021-05-27 12:55 UTC, merged