DCL/AT2: add presentation
c4dt/showcase pull request #192
Opened 2021-05-27 13:20 UTC by tharvik

Formatted version of the gdoc

2021-05-28 06:34 UTC, ineiti commented on data/DCL/projects.yaml
> +      AT2 is a full-fledged asset transfer system (cryptocurrency) without
```suggestion
      AT2 is a full-fledged asset transfer system (cryptocurrency) without the need for a global
```

2021-05-28 06:35 UTC, ineiti commented on views/incubator/at2.tpl
> +greatly reduces the total energy consumption.
Plus a paragraph on the demo-to-come.

2021-05-28 12:26 UTC, cgrigis requested changes
Minor change suggestions

2021-05-28 12:26 UTC, cgrigis commented on views/incubator/at2.tpl
> +  capabilities of Bitcoin while being orders of magnitudes faster, around 10'000
```suggestion
  capabilities as Bitcoin while being orders of magnitudes faster, around 10'000
```

2021-05-28 12:26 UTC, cgrigis commented on views/incubator/at2.tpl
> +  The main AT2 network is actually run at EPFL by some labs and interested
> The main AT2 network is actually run at EPFL by some labs and interested

Do you mean "currently" here?

2021-05-28 12:26 UTC, cgrigis commented on views/incubator/at2.tpl
> +  performing a speedtest to measure how many transactions the system can holds.
```suggestion
  performing a speedtest to measure how many transactions the system can hold.
```

2021-05-28 12:26 UTC, cgrigis commented on views/incubator/at2.tpl
> +  chain, that we graciously fill up with an initial amount of asset. You can
```suggestion
  chain, that we graciously fill up with an initial number of assets. You can
```

2021-05-28 12:26 UTC, cgrigis commented on views/incubator/at2.tpl
> +  Blockchains are around for some years now, you've probably come across the
```suggestion
  Blockchains have been around for some years now, you've probably come across the
```

2021-05-31 11:44 UTC, tharvik commented on views/incubator/at2.tpl
> +  The main AT2 network is actually run at EPFL by some labs and interested
Ho, right, fixing it :)

2021-05-31 13:33 UTC, tharvik commented
Hum, the CI fails with
```
AttributeError: 'DynamicStrictYAMLLoader' object has no attribute 'comment_handling'
../../../virtualenv/python3.6.7/lib/python3.6/site-packages/ruamel/yaml/constructor.py:1320: AttributeError
```
`ruamel.yaml` was updated today, so let's hold this PR for a day, see if any patches land.

2021-05-31 14:10 UTC, cgrigis commented
The issue has been raised to `strictyaml` as well, but for now we can fix onto the previously known-good version of `rualmel-yaml`.
#195 should fix it

2021-05-31 18:00 UTC, cgrigis approved these changes

2021-05-31 18:00 UTC, merged