DSLAB/klint: add prez
c4dt/showcase pull request #285
Opened 2022-10-07 12:01 UTC by tharvik

small prez, will probably get updated along the way.

2022-10-07 13:21 UTC, ineiti requested changes
Some typos. Just for my understanding: the source needs to include a specific library for it to work, correct? If yes, then I would rephrase a bit the description of how it works.

2022-10-07 13:21 UTC, ineiti commented on views/products/presentation/klint.tpl
> +  It works directly on binaries, without the need of special data structure.
```suggestion
  It works directly on binaries, without the need of special data structures.
```

2022-10-07 13:21 UTC, ineiti commented on views/products/presentation/klint.tpl
> +  It can ensure that a given NF, be it proprietary of not, respects a
```suggestion
  It can ensure that a given NF, be it proprietary or not, respects a
```

2022-10-07 13:21 UTC, ineiti commented on views/products/presentation/klint.tpl
> +  specification. It allows decoupling between NF-providers and network
Add `formal` in front of specification?

2022-10-07 13:48 UTC, tharvik commented
> the source needs to include a specific library for it to work, correct? If yes, then I would rephrase a bit the description of how it works.

hum, yes and no? it needs to implement two functions defined by klint but doesn't need to link w/ it nor to use it as it is then available via DPDK or tinynf implementation.

rephrasing to
>   The network functions can be written in any compiled language, as long as it exposes two functions conforming to Klint's: a setup method taking care of  initialisation, and another method handling a packet, asserting on the transmitted packet.

2022-10-10 06:37 UTC, ineiti commented on views/products/presentation/klint.tpl
> +  exposes two functions conforming to Klint's: a setup method taking care of
```suggestion
  exposes two functions conforming to Klint: a setup method taking care of
```

2022-10-10 06:37 UTC, ineiti approved these changes

2022-10-10 08:19 UTC, merged