data: adds a new entry for Anomaly Detection
c4dt/showcase pull request #319
Opened 2024-01-03 11:17 UTC by lanterno

2024-01-05 08:57 UTC, ineiti requested changes
I think we should also link to the repo you used for the project - or is there any sensitive information inside?

2024-01-05 08:57 UTC, ineiti commented on data/MLO/projects.yaml
> +    description: Runs anomaly detection algorithms in a distributed and encrypted fashion
The description should be at least 1 paragraph, better 2 paragraphs. It should describe:
- what problem it solves
- how it solves it
- why it's better than other solutions

2024-01-09 06:15 UTC, lanterno commented
@ineiti I don't think there's anything sensitive in the codebase. The repo is currently private, should I go ahead and make it public? 
Here's the link to the code to check first: https://github.com/c4dt/predictive-maintenance
The only thing that mentions RUAG is the short readme file.

2024-01-09 06:41 UTC, ineiti commented
Great - go ahead with making it public then, and link it in the showcase entry.

2024-01-09 21:17 UTC, ineiti requested changes

2024-01-09 21:17 UTC, ineiti commented on data/MLO/projects.yaml
> +    description: Runs anomaly detection algorithms in a distributed and encrypted fashion.
As we're not doing any encryption here, the description should reflect that.
```suggestion
    description: Proof-of-concept ML algorithms to do anomaly detection compatible with distributed, encrypted algorithms.
```

2024-01-10 01:02 UTC, lanterno commented on data/MLO/projects.yaml
> +    description: Runs anomaly detection algorithms in a distributed and encrypted fashion.
Makes sense. added your suggestion.

2024-01-10 07:29 UTC, ineiti approved these changes

2024-01-10 07:36 UTC, merged